<?php

function cws_aggregator_cron(){

  $total_feeds = db_query("SELECT COUNT(fid) FROM aggregator_feed")->fetchField();

  for($init_counter=1; $init_counter <= $total_feeds; $init_counter++){

    if($init_counter == 1){
    $query_string = db_select("SELECT fid FROM aggregator_feed")
    ->range(0,1);
    }
    else{
    $query_string = db_select("SELECT fid FROM aggregator_feed")
    ->range($init_counter,$init_counter);
    }
    //empty the first feed argument is fid.
    $loaded_feed = aggregator_feed_load($query_string->execute());
    aggregator_remove($loaded_feed);

    //log on recent log messages
    watchdog('cws aggregator', 'Emptied Feed: %site.', array('%site' => $loaded_feed->title));

    //load the an empty feed using aggregator_feed_load
    $empty_feed = aggregator_feed_load($query_string->execute());
    $empty_feed->source_string = "empty";
    //run update with the empty feed to fill it up
    aggregator_refresh($empty_feed);

    $filled_feed = aggregator_feed_load($query_string->execute());
    //log on recent log messages
    watchdog('cws aggregator', 'Filled Feed: %site.', array('%site' => $filled_feed->title));
  }
}
