<?php

/*
  Tables associated with aggregator:

    aggregator_category
    aggregator_category_feed
    aggregator_category_item
    aggregator_feed
    aggregator_item

*/

function cws_aggregator_cron(){

  //get the totol number of rows in the aggregator_feed table.
  $total_feeds = db_query("SELECT COUNT(fid) FROM `aggregator_feed`")->fetchField();

  //create an array that will handle multiple values using the $total_feeds value, this will store each feed's unique fid.
  //$db_feed_id = array();




  for($init_counter=1; $init_counter <= $total_feeds; $init_counter++){

    $built_query = dbquery('SELECT fid FROM aggregator_feed');
    //Prepare statements for query.
    if ($init_counter == 1)
    {
      //Get fid from only the first row
      //$built_query->range(0,1);
      //load the fid value to the current array index.
      //empty the first feed argument is fid.
      $loaded_feed = aggregator_feed_load(db_query_range($built_query, 0, 1));
      aggregator_remove($loaded_feed);

      //log on recent log messages
      watchdog('cws aggregator', 'Emptied Feed: %site.', array('%site' => $loaded_feed->title));

      //load the an empty feed using aggregator_feed_load
      $empty_feed = aggregator_feed_load(db_query_range($built_query, 0, 1));
      $empty_feed->source_string = "empty";
      //run update with the empty feed to fill it up
      aggregator_refresh($empty_feed);

      $filled_feed = aggregator_feed_load(db_query_range($built_query, 0, 1));
      //log on recent log messages
      watchdog('cws aggregator', 'Filled Feed: %site.', array('%site' => $filled_feed->title));
    }
    else {
      //load the fid value to the current array index.
      //empty the first feed argument is fid.
      $loaded_feed = aggregator_feed_load(db_query_range($built_query, $init_counter, $init_counter));
      aggregator_remove($loaded_feed);

      //log on recent log messages
      watchdog('cws aggregator', 'Emptied Feed: %site.', array('%site' => $loaded_feed->title));

      //load the an empty feed using aggregator_feed_load
      $empty_feed = aggregator_feed_load($built_query->range($built_query, $init_counter, $init_counter));
      $empty_feed->source_string = "empty";
      //run update with the empty feed to fill it up
      aggregator_refresh($empty_feed);

      $filled_feed = aggregator_feed_load($built_query->range($built_query, $init_counter, $init_counter));
      //log on recent log messages
      watchdog('cws aggregator', 'Filled Feed: %site.', array('%site' => $filled_feed->title));
    }

  }

  //unset variables from memory
  //unset($built_query);
}
